version: "3.9"

services:
  fiber-wms:
    build: .
    container_name: fiber-wms
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    restart: unless-stopped
  fiber-wms-2:
    build: .
    container_name: fiber-wms-2
    ports:
      - "9001:9000"
    env_file:
      - ./.env
    restart: unless-stopped
